create TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar,
    description varchar,
    releaseDate timestamp,
    duration    integer not null,
    rating_id   integer not null
);

create TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar UNIQUE,
    login    varchar not null UNIQUE,
    name     varchar not null,
    birthday date    not null
);

create TABLE IF NOT EXISTS friends
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   integer not null,
    friend_id integer not null,
    status    varchar not null
);

create TABLE IF NOT EXISTS likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer not null,
    user_id integer not null
);

create TABLE IF NOT EXISTS film_genre
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  integer not null,
    genre_id integer not null
);

create TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE not null
);

create TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar unique not null
);

-- Индексы для оптимизации запросов рекомендаций
CREATE INDEX IF NOT EXISTS idx_likes_user_film ON likes(user_id, film_id);
CREATE INDEX IF NOT EXISTS idx_likes_film_user ON likes(film_id, user_id);
CREATE INDEX IF NOT EXISTS idx_films_release_year ON films(YEAR(releaseDate));
CREATE INDEX IF NOT EXISTS idx_film_genre_film_genre ON film_genre(film_id, genre_id);

-- Представление для быстрого доступа к статистике
CREATE VIEW IF NOT EXISTS film_statistics AS
SELECT
    f.id as film_id,
    f.name as film_name,
    YEAR(f.releaseDate) as release_year,
    COUNT(DISTINCT l.id) as like_count,
    COUNT(DISTINCT fg.genre_id) as genre_count
FROM films f
LEFT JOIN likes l ON f.id = l.film_id
LEFT JOIN film_genre fg ON f.id = fg.film_id
GROUP BY f.id;