create TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    releaseDate timestamp,
    duration integer not null,
    rating varchar not null
);

create TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar UNIQUE,
    login varchar not null UNIQUE,
    name varchar not null,
    birthday date not null
);

create TABLE IF NOT EXISTS friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer not null,
    friend_id integer not null,
    status varchar not null
);

create TABLE IF NOT EXISTS likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer not null,
    user_id integer not null
);

create TABLE IF NOT EXISTS film_genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer not null,
    genre_id integer not null
);

create TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar UNIQUE not null
);

create TABLE IF NOT EXISTS Rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar unique not null
);